version: '2'

services:

  app:
    build:
      context: .
    volumes:
      - "./src:/app/src"
      - "./test:/app/test"
      - "./Makefile:/app/Makefile"
    environment:
      NODE_ENV: development
    ports:
      - "3072:8080" 
    logging:
      options:
        max-size: "5k"
